import http from 'node:http';import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const html=fs.readFileSync(new URL('../docs/macbook.html',import.meta.url));const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end(html);});await new Promise(r=>server.listen(4323,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true});for(const viewport of [{width:1440,height:900},{width:390,height:844}]){const context=await browser.newContext({viewport});const page=await context.newPage();let stored={enabled:true,minBatteryPercent:50,pollIntervalMinutes:10,requireAC:true,requireHome:true};
 await page.addInitScript(()=>localStorage.setItem('promptr_qa_dash_key','test-key'));
 await page.route('https://promptr-qa-dashboard.vercel.app/api/macbook',async route=>{if(route.request().method()==='POST'){assert.equal(route.request().headers()['x-dash-key'],'test-key');stored=route.request().postDataJSON().settings;await route.fulfill({headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-dash-key','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},json:{ok:true,settings:stored}});}else await route.fulfill({headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-dash-key','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},json:{writable:true,settings:stored}});});
 await page.goto('http://localhost:4323/macbook.html');await page.getByRole('button',{name:'Save settings',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('button[type="submit"]')?.disabled===false||[...document.querySelectorAll('button')].some(b=>b.textContent==='Save settings'&&!b.disabled));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile/desktop page overflow');
 await page.getByRole('textbox',{name:'Minimum battery percent',exact:true}).fill('55');await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.waitForFunction(()=>document.body.textContent.includes('battery>55%'));assert.equal(stored.minBatteryPercent,55);
 await page.getByRole('checkbox',{name:'Require AC power',exact:true}).uncheck();assert.equal(await page.getByRole('checkbox',{name:'Require AC power',exact:true}).isChecked(),false);await context.close();console.log(`MacBook controls verified at ${viewport.width}x${viewport.height}`);
 }}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
